project:
  type: website

website:
  title: "Run R code on GitHub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
        
  page-footer: 
    center: "© Morten Lorenzen 2024"
    background: light        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



